services:
  app:
    image: 'vaquejada-pro-backend:latest'
    build:
      context: .
    container_name: api
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL:-jdbc:postgresql://db:${DB_PORT:-5432}/${POSTGRES_DB:-db}}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-${POSTGRES_USER:-postgres}}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD:-admin}}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO:-none}
      - SPRING_OPEN_IN_VIEW=${OPEN_IN_VIEW:-false}
      - SECURITY_JWT_TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY:-secret}
      - SECURITY_JWT_TOKEN_EXPIRE_LENGTH=${TOKEN_EXPIRE_LENGTH:-3600000}
      - SECURITY_JWT_REFRESH_TOKEN_EXPIRE_LENGTH=${REFRESH_TOKEN_EXPIRE_LENGTH:-10800000}
    ports:
      - ${API_PORT:-8080}:8080

  db:
    image: postgres
    container_name: database
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-db}
    ports:
      - ${DB_PORT:-5432}:5432