services:
  app:
    image: 'vaquejada-pro-api:latest'
    build:
      context: .
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_OPEN_IN_VIEW=${SPRING_OPEN_IN_VIEW}
      - SECURITY_JWT_TOKEN_SECRET_KEY=${SECURITY_JWT_TOKEN_SECRET_KEY}
      - SECURITY_JWT_TOKEN_EXPIRE_LENGTH=${SECURITY_JWT_TOKEN_EXPIRE_LENGTH}
      - SECURITY_JWT_REFRESH_TOKEN_EXPIRE_LENGTH=${SECURITY_JWT_REFRESH_TOKEN_EXPIRE_LENGTH}
    ports:
      - "${APP_PORT}:8080"

  db:
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    shm_size: 128mb
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}