# Example connection URL: jdbc:postgresql://localhost:5432/your-database
spring:
  datasource:
    url: jdbc:postgresql://localhost:3030/db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

security:
  jwt:
    token:
      secret-key: secret # JWT secret key (any string)
      expire-length: 3600000 # JWT token expiration time (1 hour = 3,600,000 ms)
    refresh-token:
      expire-length: 10800000 # JWT refresh token expiration time (3 hours = 10,800,000 ms)

server:
  port: 8080
